# Generated by Django 6.0 on 2025-12-18 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('marital_status', models.CharField(choices=[('S', 'Холост/Не замужем'), ('M', 'Женат/Замужем'), ('D', 'Разведен(а)'), ('W', 'Вдовец/Вдова')], max_length=1, verbose_name='Семейное положение')),
                ('has_children', models.BooleanField(default=False, verbose_name='Наличие детей')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ученая степень')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавлен пользователем')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
    ]
